# Generated by Django 5.0.6 on 2024-05-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('task_id', models.CharField(max_length=8, unique=True)),
                ('task_name', models.CharField(max_length=128)),
                ('task_description', models.TextField(max_length=255, null=True)),
                ('task_deadline', models.TextField(max_length=32, null=True)),
                ('task_priority', models.IntegerField()),
                ('task_status', models.IntegerField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
