# Generated by Django 5.0.6 on 2024-05-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
